services:
  jupyter:
    image: quay.io/jupyter/minimal-notebook:2026-04-20 # or latest
    container_name: ai-bootcamp
    volumes:
      - ./:/home/jovyan/work # maps the repo's root dir to the container's work dir
    ports:
      - "${DOCKER_COMPOSE_JUPYTER_PORT:-8888}:8888"
    environment:
      - HF_TOKEN=${HF_TOKEN}
